### Hello World
GET http://localhost:8080/api/hello

### GetMapping hello
GET http://localhost:8080/api/get/hello

### RequestMapping GET hi
GET http://localhost:8080/api/get/hi

### PathVariable
// http://localhost:{port}/api/get/path-variable/{name}
GET http://localhost:8080/api/get/path-variable/hello

### QueryParam
// http://localhost:{port}/api/get/query-param
GET http://localhost:8080/api/get/query-param?name=master&email=master@gmail.com&age=10

### QueryParam2
// http://localhost:{port}/api/get/query-param2
GET http://localhost:8080/api/get/query-param2?name=master&email=master@gmail.com&age=10

### QueryParam3
// http://localhost:{port}/api/get/query-param3
GET http://localhost:8080/api/get/query-param3?name=master&email=master@gmail.com&age=10

### POST API
POST http://localhost:8080/api/post
Content-Type: application/json

{
  "account": "user01",
  "email": "user@gmail.com",
  "address": "패스트캠퍼스",
  "password": "abcd"
}

### POST Request DTO API
POST http://localhost:8080/api/post-request
Content-Type: application/json

{
  "account": "user01",
  "email": "user@gmail.com",
  "address": "패스트캠퍼스",
  "password": "abcd",
  "phone_number": "010-1234-1234"
}

### PUT Request DTO API
// http://localhost:8080/api/put/{userId}
PUT http://localhost:8080/api/put/100
Content-Type: application/json

{
  "name": "master",
  "age": 20,
  "car_list": [
    {
      "name": "BMW",
      "car_number": "11가 1234"
    },
    {
      "name": "A4",
      "car_number": "22가 3456"
    }
  ]
}

### DELETE API
// http://localhost:8080/api/delete/{userId}
DELETE http://localhost:8080/api/delete/100?account=user100

### GET Text Response
GET http://localhost:8080/api/text?account=user100

### POST Json Response
POST http://localhost:8080/api/json
Content-Type: application/json

{
  "name": "master",
  "age": 10,
  "phone_number": "010-1234-12334",
  "address": "패스트캠퍼스"
}

### PUT ResponseEntity Json Response
PUT http://localhost:8080/api/put
Content-Type: application/json

{
  "name": "master",
  "age": 10,
  "phone_number": "010-1234-12334",
  "address": "패스트캠퍼스"
}

### GET main page
GET http://localhost:8080/main

### GET User ResponseBody Response
GET http://localhost:8080/user
